//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagaji.Services.SagajiMitPagos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wstrans.cpagos", ConfigurationName="SagajiMitPagos.xmltransaccionesPortType")]
    public interface xmltransaccionesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string transaccionesCargosAutomaticos(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> transaccionesCargosAutomaticosAsync(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string transacciones(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> transaccionesAsync(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string transaccionesDomiciliacion(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> transaccionesDomiciliacionAsync(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string cancelacionesCargosAutomaticos(string in0, string in1, string in2, string in3, string in4, string in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> cancelacionesCargosAutomaticosAsync(string in0, string in1, string in2, string in3, string in4, string in5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface xmltransaccionesPortTypeChannel : Sagaji.Services.SagajiMitPagos.xmltransaccionesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class xmltransaccionesPortTypeClient : System.ServiceModel.ClientBase<Sagaji.Services.SagajiMitPagos.xmltransaccionesPortType>, Sagaji.Services.SagajiMitPagos.xmltransaccionesPortType {
        
        public xmltransaccionesPortTypeClient() {
        }
        
        public xmltransaccionesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public xmltransaccionesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public xmltransaccionesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public xmltransaccionesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string transaccionesCargosAutomaticos(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.transaccionesCargosAutomaticos(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<string> transaccionesCargosAutomaticosAsync(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.transaccionesCargosAutomaticosAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public string transacciones(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.transacciones(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<string> transaccionesAsync(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.transaccionesAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public string transaccionesDomiciliacion(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.transaccionesDomiciliacion(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<string> transaccionesDomiciliacionAsync(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.transaccionesDomiciliacionAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public string cancelacionesCargosAutomaticos(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.cancelacionesCargosAutomaticos(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<string> cancelacionesCargosAutomaticosAsync(string in0, string in1, string in2, string in3, string in4, string in5) {
            return base.Channel.cancelacionesCargosAutomaticosAsync(in0, in1, in2, in3, in4, in5);
        }
    }
}
