//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSIS.SagajiServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_version
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public app_version()
        {
            this.descarga_clientes = new HashSet<descarga_clientes>();
        }
    
        public string app_id { get; set; }
        public short plataforma_id { get; set; }
        public Nullable<System.DateTime> liberacion { get; set; }
        public string version { get; set; }
        public byte[] app { get; set; }
    
        public virtual plataforma plataforma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<descarga_clientes> descarga_clientes { get; set; }
    }
}
