//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagaji.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo_csv
    {
        public string cat_id { get; set; }
        public Nullable<System.DateTime> register { get; set; }
        public byte[] cat_info { get; set; }
    }
}
