//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagaji.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class descarga_clientes
    {
        public string app_id { get; set; }
        public short plataforma_id { get; set; }
        public string nocliente { get; set; }
        public Nullable<System.DateTime> fecha_descarga { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual app_version app_version { get; set; }
        public virtual cliente_info cliente_info { get; set; }
    }
}
