//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagaji.Services.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KEPLEREntities : DbContext
    {
        public KEPLEREntities()
            : base("name=KEPLEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KDII> KDII { get; set; }
        public virtual DbSet<KDUDENT> KDUDENT { get; set; }
        public virtual DbSet<KIUSRS> KIUSRS { get; set; }
    }
}
