//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sagaji.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_logger
    {
        public decimal logger_id { get; set; }
        public short id_status { get; set; }
        public string login { get; set; }
        public string cvepedido { get; set; }
        public Nullable<System.DateTime> register_event { get; set; }
        public string message { get; set; }
    
        public virtual event_status event_status { get; set; }
    }
}
